version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
          path: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "signinwithapplebutton/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "signinwithapplebutton/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean assemble
      - run:
          name: Check
          command: ./gradlew lintRelease
      - store_artifacts:
          path: signinwithapplebutton/build/outputs/
          destination: core
#      - store_test_results:
#          path: app/build/test-results
# TODO: Add deploy step when we are ready to publish
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: opensource-maven
